// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TooGoodToGoNotifier.Models;

#nullable disable

namespace TooGoodToGoNotifier.Migrations
{
    [DbContext(typeof(TooGoodToGoNotifierContext))]
    partial class TooGoodToGoNotifierContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("TooGoodToGoNotifier.Models.Basket", b =>
                {
                    b.Property<string>("BasketId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("BasketId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("TooGoodToGoNotifier.Models.Store", b =>
                {
                    b.Property<string>("StoreId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("StoreId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("TooGoodToGoNotifier.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TooGoodToGoNotifier.Models.Basket", b =>
                {
                    b.HasOne("TooGoodToGoNotifier.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId");

                    b.HasOne("TooGoodToGoNotifier.Models.User", null)
                        .WithMany("FavoriteBaskets")
                        .HasForeignKey("UserId");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("TooGoodToGoNotifier.Models.User", b =>
                {
                    b.Navigation("FavoriteBaskets");
                });
#pragma warning restore 612, 618
        }
    }
}
