# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/workflows/release.yml"
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build
        run: dotnet build --configuration Release
